@startuml
:Parse args;

label Visit_Page
:Add node to graph;
if (GET request for page returns?) then (yes)
    :Parse document;
    :Get Links;
    if (Page already visited?) then (no)
        goto Visit_Page
    else
        stop
    endif
else (no)
    :Mark node as bad;
    stop
endif



note
Each page = 1 node in the graph.
Total pages checked = Total nodes in graph.

Link in page A to page B expressed 
as edge from node A to node B.

Each node has a weight: 
-1 = bad
0 = not checked
1 = good
end note

@enduml