[package]
name = "spider-crab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
reqwest = "0.11.22"
scraper = "0.18.1"
tokio =  { version = "1.33.0", features=["full"] }
