on:
    pull_request:
    push:
      branches:
        - main
  

name: Format, Lint and Test

jobs:
    check:
        name: Cargo Check
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: cargo check

    fmt:
        name: Formatter Check
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: cargo fmt --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: cargo clippy --no-deps

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: cargo test