name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Release
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked
    - name: Upload
      uses: ncipollo/release-action@v1
      with:
        artifacts: target/release/spider-crab
        tag: ${{ github.ref }}
        allowUpdates: false
