name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
    - uses: actions/checkout@v3
    - name: Format Check
      run: cargo fmt --check
    - name: Linter Check
      run: cargo clippy --no-deps
    - name: Cargo Test
      run: cargo test
    - name: Build
      run: cargo build --verbose
